config/routes.rb
BaixoSom::Application.routes.draw do

    root :to => "bandas#index"

 match 'bandas/:letra' => "bandas#index", :constraints => {:id => /\w/}
    
    resources :links, :torrents, :votos, :users, :bandas, :albuns, :votos

    match "login" => "users#login"
    match "logout" => "users#logout"    
    match "novo_usuario" => "users#novo"
    match "pesquisa" => "pesquisa#pesquisa"
    match 'sitemap.xml' => "sitemap#sitemap", :defaults => {:format => :xml}

    match 'nova_banda' => "bandas#new"
    match 'pessoa/:user' => "users#show"
    match 'pessoa/update/:id' => "users#update_status"

    match 'torrents/upload' => "torrents#upload"
    match 'torrent/:fixhash' => 'torrents#show', :requirements => { :fixhash => /\w{40}/ }
    match 'download/:fixhash' => 'torrents#download', :requirements => { :fixhash => /\w{40}/ }

    match ':banda' => "bandas#show"
    match ':banda/novo_album' => "albuns#new"
    match ':banda/:album' => "albuns#show"
    match ':banda/:album/novo_link' => "links#new"

    match 'album/editar/:id' => "albuns#edit"
    match 'album/excluir/:id' => "albuns#excluir"
    match 'album/destroy/:id' => "albuns#destroy"    

end

app/models/banda.rb
# encoding: UTF-8
class Banda < ActiveRecord::Base
  belongs_to :user
  has_many :albuns, :dependent => :destroy  

  validates_uniqueness_of :nome, :message=>"já foi inserido"
  validates_uniqueness_of :atalho
  validates_presence_of :nome, :user
  validates_length_of :nome, :in=>2..55, :message=>"deve ter entre 2 e 55 caracteres"
  before_create :urlize

  def self.find_by_letra(letter)
    if letter=="9"
      find(:all, :conditions => ['nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ? OR nome LIKE ?', "#{0}%", "#{1}%", "#{2}%", "#{3}%", "#{4}%", "#{5}%", "#{6}%", "#{7}%", "#{8}%", "#{9}%"], :order => 'nome ASC')
    else
      find(:all, :conditions => ['nome LIKE ?', "#{letter}%"], :order => 'nome ASC')
    end
  end

  private
  def urlize
    self.nome.strip!
    self.atalho = nome.urlize({:downcase=>true, :convert_spaces=>true})
  end

    # algumas
    def self.algumas
        Banda.find :all, :offset => (Banda.count * rand ).to_i ,:limit=>10
  end
end

app/controllers/bandas_controller.rb
# encoding: UTF-8
class BandasController < ApplicationController
  # GET /bandas
  # GET /bandas.xml
  def index
    letra = params[:letra]
    @bandas = letra ? Banda.find_by_letra(letra) : []
puts letra
puts "#"*20
    @bandas_count = Banda.count
    @albuns_count = Album.count
    @users_count = User.confirmado.count

    @algumas_bandas = Banda.find(:all, :offset => (Banda.count * rand - 10).to_i ,:limit=>10)
    @ultimos_albuns = Album.ultimos
    @usuarios_ativos = User.ativos
    #@dominios_utilizados = Link.utilizados

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bandas }
    end
  end

  # GET /bandas/1
  # GET /bandas/1.xml
  def show
    @banda = Banda.find_by_atalho(params[:banda])
    
    if !@banda
      flash[:notice] = "Não existe essa banda aqui. Adicione!"
      redirect_to("/")
      return
    else
      @page_title = @banda.nome
    end
    
    @banda_albuns = Album.find_all_by_banda_id(@banda.id, :order=>"ano")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @banda }
    end
  end

  # GET /bandas/new
  # GET /bandas/new.xml
  def new
    @banda = Banda.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @banda }
    end
  end

  # GET /bandas/1/edit
  def edit
    @banda = Banda.find(params[:id])
  end

  # POST /bandas
  # POST /bandas.xml
  def create
    @banda = Banda.new(params[:banda])
    @banda.user_id = session[:user]
    
    respond_to do |format|
      if @banda.save
        flash[:notice] = "A nova banda foi adicionada."
        format.html { redirect_to("/#{@banda.atalho}/novo_album", :banda=>@banda) }
      else
        format.html { render :action => "new" }
      end
    end
  end

end

app/views/bandas/index.html.haml
- letra =  params[:letra] == "9" ? "#" : params[:letra]
%h1= "Letra | #{letra.upcase}" if letra
- if @bandas.size > 0
  %ul
    - @bandas.each do |banda|
      %li
        = link_to "#{banda.nome} (#{banda.albuns.count})", banda_path(banda)
%br/
- if @bandas.size==0 && !params[:letra]
  %table
    %tr{:valign => "top"}
      %td{:width => "200px"}
        %h3{:style => "font-size:19px"} Algumas Bandas
      %td{:width => "180px"}
        %h3{:style => "font-size:19px"} Membros Ativos
      %td
        %h3{:style => "font-size:19px"} Últimas Bandas
    %tr
      %td{:valign => "top"}
        %ul
          - @algumas_bandas.each do |alguma_banda|
            %li
              = link_to alguma_banda.nome, banda_path(alguma_banda)
      %td{:valign => "top"}
        %ul
          - @usuarios_ativos.each do |usuario|
            %li
              = link_to "#{usuario.username} (#{usuario.links_count})", user_path(usuario)
      %td{:valign => "top"}
        %ul
          - @ultimos_albuns.each do |album|
            %li
              = link_to album_name(album), album_path(album)
  %br/
  - else if @bandas.size==0
    %p{:style => "font-size:15px"}= "Nenhuma banda com #{letra.upcase} foi inserida ainda."
%br/
= link_to 'Adicionar Banda', "/nova_banda", {:class=>'butao'}
%br
%br
%br

app/views/bandas/new.html.haml
:javascript
  document.title = "BaixoGavea.com | Adicionar Banda"
%h1 Nova Banda ou Artista
- form_for(@banda) do |f|
  = f.error_messages
  %p
    = f.label :nome
    %br/
    = f.text_field :nome
  %p
    = f.submit 'Criar', {:class=>'butao'}
%br/
= link_to 'Voltar', bandas_path

app/views/bandas/pesquisa.html.haml
- if @albuns.size == 0 &&  @bandas.size == 0
  %p Nenhum resultado.
  %br/
- if @albuns.size > 0
  %h2 Bandas
  %ul
    - @bandas.each do |banda|
      %li
        = link_to banda.nome, banda_path(banda)
- if @albuns.size > 0
  %h2 Álbuns
  %ul
    - @albuns.each do |album|
      %li
        = link_to album.nome, album_path(banda)
= link_to "Voltar", "javascript:back()"

app/views/bandas/show.html.haml
#fixo
  %h1= h @banda.nome
  - albuns = @banda.albuns.count
  = link_to 'Adicionar Álbum', new_album_path(@banda)
  %p{:style => "font-size:12px"}= pluralize(albuns, "álbum", "álbuns")

- if @banda_albuns.size > 0
  - x=0
  %table{:cellspacing => "15px", :style => "margin-left:-15px"}    
    %tr    
      - @banda_albuns.each do |album|
        %td{:align => "center", :valign => "top", :width => "180px"}
          = link_to album_image(album), album_path(album)
          %br
          = link_to "#{album.nome} (#{album.ano})", album_path(album)
          - x = x+1
          - if x % 4 == 0
            %tr/
  %br
- else
  %p Nenhum álbum foi adicionado ainda.