config/routes.rb
BaixoSom::Application.routes.draw do

    root :to => "bandas#index"

 match 'bandas/:letra' => "bandas#index", :constraints => {:id => /\w/}
    
    resources :links, :torrents, :votos, :users, :bandas, :albuns, :votos

    match "login" => "users#login"
    match "logout" => "users#logout"    
    match "novo_usuario" => "users#novo"
    match "pesquisa" => "pesquisa#pesquisa"
    match 'sitemap.xml' => "sitemap#sitemap", :defaults => {:format => :xml}

    match 'nova_banda' => "bandas#new"
    match 'pessoa/:user' => "users#show"
    match 'pessoa/update/:id' => "users#update_status"

    match 'torrents/upload' => "torrents#upload"
    match 'torrent/:fixhash' => 'torrents#show', :requirements => { :fixhash => /\w{40}/ }
    match 'download/:fixhash' => 'torrents#download', :requirements => { :fixhash => /\w{40}/ }

    match ':banda' => "bandas#show"
    match ':banda/novo_album' => "albuns#new"
    match ':banda/:album' => "albuns#show"
    match ':banda/:album/novo_link' => "links#new"

    match 'album/editar/:id' => "albuns#edit"
    match 'album/excluir/:id' => "albuns#excluir"
    match 'album/destroy/:id' => "albuns#destroy"    

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  scope :confirmado, where(:confirmado=>true)
  scope :ultimos, where(:confirmado=>true).limit(10)

  has_many :links
  has_many :albuns
  has_many :bandas
  has_many :votos

  validates_uniqueness_of :username, :email, :message=>"já foi inserido"
  validates_uniqueness_of :normalizado, :message=>". Escolha outro username"
  validates_presence_of :username, :info, :email, :senha
  validates_format_of :email, :with=>/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/
  validates_length_of :senha, :in=>6..15, :message=>"deve ter entre 6 e 15 caracteres"
  validates_length_of :username, :in=>4..15, :message=>"deve ter entre 4 e 15 caracteres"

  # retira espaços do username
  def before_validation
    self.username.gsub!(" ", "")
    self.normalizado = self.username.downcase
    self.username = self.username.urlize({:downcase=>false, :convert_spaces=>false})
  end

  # envia confirmação de cadastro
  def after_create
    Carteiro.deliver_confirme(self)
  end

  # gera hash para validação do usuário
  def gera_cod_valid
    user = self
    str_cod = user.email+user.username+user.senha+user.created_at.to_s
    Digest::MD5.hexdigest(str_cod)
  end

  # usuarios que adicionaram mais links
  def self.ativos
    find(
      :all,
      :limit=>10,
      :joins=>:links,
      :group=>"links.user_id",
      :select=>"*, COUNT(links.id) as links_count",
      :order => 'links_count DESC'
    )
  end

end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < ApplicationController

  def login
    if params[:user]
      log_user = params[:user]
      @user = User.find_by_username_and_confirmado(log_user[:username], "1")
      if !@user
        flash[:notice] = "Usuário não existe."
      else
      	if @user.senha == log_user[:senha]
          session[:user] = @user.id
          session[:username] = @user.username
          session[:logged] = true
          flash[:notice] = "Bem-Vindo #{@user.username}!"
          @user.lastlogin_at = DateTime.now
          @user.save
          redirect_to session[:href] ? session[:href] : "/"
        	return true
        else
          flash[:notice] = "Senha incorreta!"
        end
      end
    end

    respond_to do |format|     
      format.html
    end
  end

  def logout
    session[:user] = nil
    session[:username] = nil
    session[:logged] = false
    flash[:notice] = "Tchau!"
    redirect_to request.referrer
  end

  def show
    @user = User.find_by_username_and_confirmado(params[:user], "1")
    
    if @user==nil && params[:valid]
      # validação
      user_not_confirmed = User.find_by_username(params[:user])
      if user_not_confirmed
        validation = user_not_confirmed.gera_cod_valid
        if params[:valid] == validation
          user_not_confirmed.confirmado=1
          user_not_confirmed.save
          user = user_not_confirmed
          # agora tá confirmado
          flash[:notice] = "Ativado! Bem-Vindo #{params[:user]}."
          session[:user] = user.id
          session[:username] = user.username
          session[:logged] = true
          @user = user
        else
          flash[:notice] = "Código de validação inválido."
        end
      end
    else
      if @user==nil
        flash[:notice] = "Usuário #{params[:user]} não existe."
      else
        @bandas_count = Banda.count(:conditions=>{:user_id=>@user})
        @albuns_count = Album.count(:conditions=>{:user_id=>@user})
        @links_count = Link.count(:conditions=>{:user_id=>@user})
      end
    end

    respond_to do |format|
      if @user
        @user_albuns = Album.find_all_by_user_id(@user.id, :order=>"created_at DESC")
        format.html # show.html.erb
      else
        format.html {redirect_to(bandas_path)}
      end
    end
  end

  def novo
    @user = User.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:notice] = "Usuário #{@user.username} adicionado. Verifique seu email para concluir o cadastro."
        format.html { redirect_to(bandas_path)}
      else
        format.html { render :action => "novo" }
      end
    end
  end

  # atualiza user.info (bioline) por ajax
  def update_status
    new_info = params[:user][:info]
    my_id = session[:user].to_i
    # se estou editando minha info, update
    if my_id == params[:id].to_i && new_info
      user = User.update(my_id , {:info=>new_info})
      render :json => {:info=>user.reload.info}.to_json, :status=>200
    else
      render :nothing => true, :status=>500
    end

  end

end

app/views/users/login.html.haml
%h1 Autenticação
= form_for :user, :url => { :action => "login" } do |f|
  %p
    = f.label :username
    %br/
    = f.text_field :username
  %p
    = f.label :senha
    %br/
    = f.password_field :senha
  %p
    = f.submit 'Entrar'
%br/
= link_to 'Voltar', "javascript:back()"
|
\#{link_to 'Novo Usuário', "novo_usuario"}

app/views/users/novo.html.haml
%h1 Novo usuário
- form_for :user, :url => { :action => "create" } do |f|
  = f.error_messages
  %p
    = f.label :username
    (login)
    %br/
    = f.text_field :username
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :senha
    %br/
    = f.password_field :senha
  %p
    = f.label :info
    (frase do perfil)
    %br/
    = f.text_field :info
  %p
    = f.submit 'Criar'
= link_to 'Voltar', "javascript:back()"

app/views/users/show.html.haml
= javascript_include_tag 'editable'
:javascript
  document.title = "BaixoGavea.com | Usuário | #{@user.username}";
  document.observe('dom:loaded', function(event) {
    Editable.setupAll();
  });
%table
  %tr
    %td= image_tag "user.png", {:style=>"margin-right:5px"}
    %td{:valign => "top"}
      %h1= @user.username
%p{:style => "font-size:15px"}
  - if @user.id == session[:user]
    = edit_in_place(@user, :info, :rel=>"/user/update/#{@user.id}")
  - else
    = @user.info
%table{:cellspacing => "5"}
  - @user_albuns.each do |album|
    %tr
      - if @user.id == session[:user]
        %td
          <a title="Editar" href="#{editar_album_path(album)}"#{image_tag "link_edit.png"}
        %td
          <a title="Excluir" href="#{excluir_album_path(album)}"#{image_tag "link_del.png"}
      %td
        = link_to album_name(album), album_path(album)
      %td
%p{:style => "font-size:15px; padding-left:8px"}
  = "#{@bandas_count} bandas > #{@albuns_count} álbuns > #{@links_count} liames"