config/routes.rb
BaixoSom::Application.routes.draw do

    root :to => "bandas#index"

 match 'bandas/:letra' => "bandas#index", :constraints => {:id => /\w/}
    
    resources :links, :torrents, :votos, :users, :bandas, :albuns, :votos

    match "login" => "users#login"
    match "logout" => "users#logout"    
    match "novo_usuario" => "users#novo"
    match "pesquisa" => "pesquisa#pesquisa"
    match 'sitemap.xml' => "sitemap#sitemap", :defaults => {:format => :xml}

    match 'nova_banda' => "bandas#new"
    match 'pessoa/:user' => "users#show"
    match 'pessoa/update/:id' => "users#update_status"

    match 'torrents/upload' => "torrents#upload"
    match 'torrent/:fixhash' => 'torrents#show', :requirements => { :fixhash => /\w{40}/ }
    match 'download/:fixhash' => 'torrents#download', :requirements => { :fixhash => /\w{40}/ }

    match ':banda' => "bandas#show"
    match ':banda/novo_album' => "albuns#new"
    match ':banda/:album' => "albuns#show"
    match ':banda/:album/novo_link' => "links#new"

    match 'album/editar/:id' => "albuns#edit"
    match 'album/excluir/:id' => "albuns#excluir"
    match 'album/destroy/:id' => "albuns#destroy"    

end

app/controllers/albuns_controller.rb
# encoding: UTF-8
class AlbunsController < ApplicationController

  def index
    @albuns = Album.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    banda = Banda.find_by_atalho(params[:banda])

    unless banda
      flash[:notice] = "Não existe essa banda aqui. Adicione!"
      redirect_to("/")
      return
    end

    @album = Album.find_by_atalho_and_banda_id(params[:album], banda)
    unless @album
      flash[:notice] = "Não existe esse álbum aqui. Adicione!"
      redirect_to("/"+banda.atalho)
      return
    end
    @page_title = banda.nome + " | " + @album.nome

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  def new
    @album = Album.new
    @banda = Banda.find_by_atalho(params[:banda])

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @album = Album.find(params[:id])
    if @album.user.id != session[:user]
      flash[:notice] = "Você só pode editar as bandas que adicionou."
      redirect_to("/")
      return
    end
  end

  def new_album_link(album)
    "/#{album.banda.atalho}/#{album.atalho}/novo_link"
  end

  def create
    album = params[:album]
    album["ano"] = album["ano(1i)"]
    album.delete("ano(1i)")
    album.delete("ano(2i)")
    album.delete("ano(3i)")
    @album = Album.new(album)
    @banda = @album.banda
    @album.user_id = session[:user]
    
    respond_to do |format|
      if @album.save
        flash[:notice] = "O novo álbum foi adicionado."
        format.html { redirect_to(new_album_link(@album), :banda=>@album.banda.atalho, :album=>@album.atalho) }
        format.xml  { render :xml => @album, :status => :created, :location => @album.atalho }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @album = Album.find(params[:id])

    if @album.user.id != session[:user]
      flash[:notice] = "Você só pode editar as bandas que adicionou."
      redirect_to("/")
      return
    end

    respond_to do |format|
      album = params[:album]
      album["ano"] = album["ano(1i)"]
      album.delete("ano(1i)")
      album.delete("ano(2i)")
      album.delete("ano(3i)")
      if @album.update_attributes(album)
        flash[:notice] = 'O Álbum foi editado com sucesso.'
        format.html { redirect_to("/#{@album.banda.atalho}/#{@album.atalho}/") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # pré
  def excluir
    @album = Album.find(params[:id])
    #album.destroy
    flash[:notice] = "Hey! Mesmo, mesmo, #{session[:username]}?"
  end

  def destroy
    @album = Album.find(params[:id])
    user = @album.user
    if session[:user] == user.id
      @album.destroy
      flash[:notice] = 'Álbum excluído!'
    else
      flash[:notice] = 'Você só pode excluir o que adicionou!'
    end

    puts user_path(user)
    respond_to do |format|
      format.html {redirect_to("/usuario/#{user.username}")}
    end
  end

end

app/views/albuns/edit.html.haml
:javascript
  document.title = "BaixoGavea.com | Editar | #{@album.nome}"
%div{:style => "float: left; padding-right:15px"}= album_image(@album)
%h1= "Editar | #{@album.banda.nome} - #{@album.nome} (#{@album.ano})"
- form_for(@album, :url => { :action => "update"}) do |f|
  = f.error_messages
  = hidden_field_tag("album[banda_id]", @album.banda.id)
  = hidden_field_tag("album[user_id]", session[:user])
  %p
    = f.label :nome
    %br/
    = f.text_field :nome
    \&nbsp;
    \#{f.label :ano}
    \#{f.date_select :ano,  :discard_day => true, :discard_month => true, :start_year => 1950, :end_year=>Time.now.year}
  %p
    = f.submit 'Atualizar'
%br/
%br/
= link_to "Voltar", "javascript:back()"

app/views/albuns/excluir.html.haml
:javascript
  document.title = "BaixoGavea.com | Excluir | #{@album.nome}"
%table
  %tr
    %td
      %div{:style => "float: left; padding-right:15px"}= album_image(@album)
    %td{:align => "center", :valign => "middle"}
      %h2= "Tem certeza que deseja excluir<br>#{@album.banda.nome} - #{@album.nome} (#{@album.ano})<br>e todos seus liames e comentários?"
      %br/
      = link_to "Não", "javascript:back()"
      | #{link_to "Sim",  destroy_album_path(@album)}

app/views/albuns/index.html.haml
%h1 Álbuns
%table
  %tr
    %th Nome
  - @albuns.each do |album|
    %tr
      %td= link_to "#{album.banda.nome} - #{album.nome}", album_path(album)

app/views/albuns/new.html.haml
:javascript
  document.title = "BaixoGavea.com | Adicionar Álbum"
%h1
  Novo Álbum | #{@banda.nome}
- form_for :album, :url => { :action => "create" } do |f|
  = hidden_field_tag("album[banda_id]", @banda.id)
  %p
    = f.label :nome
    %br/
    = f.text_field :nome
    \&nbsp;&nbsp;
    \#{f.date_select :ano, :discard_day => true, :discard_month => true, :start_year => 1950, :end_year=>Time.now.year}
  %p
    = f.submit 'Criar'
%br/
= link_to 'Voltar', banda_path(@banda)

app/views/albuns/show.html.haml
%div{:style => "float: left; padding-right:15px"}= album_image(@album)
%br/
%h2= "#{@album.banda.nome} - #{@album.nome} (#{@album.ano})"
%br/
#album_menu{:style => "height:110px"}
  = link_to 'Voltar', banda_path(@album.banda)
  |
  = link_to 'Adicionar Link', new_link_path(@album)
  |
  = link_to "Adicionar Torrent", "javascript:addTorrent()"
  - if @album.user.id == session[:user]
    |
    = link_to "Editar", editar_album_path(@album)
  = render :partial => "torrents/upload_torrent"
- if @album.links.size > 0
  %table{:cellpadding => "5", :style => "margin:5px"}
    %tr
      %th{:align => "left"}
        = image_tag "liame.png", {:style=>"padding-right:5px; float:left"}
        Liames
      %th Semeadores
      %th Arquivos
      %th Tamanho
    - @album.links.each do |link|
      %tr{:style => ""}
        - unless link.is_torrent
          %td
            = link_to "Link de #{link.tracker.nome}", link_path(link), { :rel => 'nofollow' }
          %td{:align => "center"} -
          %td{:align => "center"} -
          %td{:align => "center"} -
        - else
          %td
            = link_to "#{link.torrent.nome}", link.url, { :rel => 'nofollow' }
          %td{:align => "center", :style => "color:green; font-size:14px", :valign => "middle"}
            = link.torrent.total_seeds
          %td{:align => "center", :valign => "middle"}
            %div{:style => "font-size:14px"}= link.torrent.arquivos.size
          %td{:align => "center", :valign => "middle"}
            %div{:style => "font-size:14px"}= to_size(link.torrent.size)
- else
  %p{:style => "font-size:15px"}
    %br>/
    Nenhum liame foi adicionado ainda.