config/routes.rb
BaixoSom::Application.routes.draw do

    root :to => "bandas#index"

 match 'bandas/:letra' => "bandas#index", :constraints => {:id => /\w/}
    
    resources :links, :torrents, :votos, :users, :bandas, :albuns, :votos

    match "login" => "users#login"
    match "logout" => "users#logout"    
    match "novo_usuario" => "users#novo"
    match "pesquisa" => "pesquisa#pesquisa"
    match 'sitemap.xml' => "sitemap#sitemap", :defaults => {:format => :xml}

    match 'nova_banda' => "bandas#new"
    match 'pessoa/:user' => "users#show"
    match 'pessoa/update/:id' => "users#update_status"

    match 'torrents/upload' => "torrents#upload"
    match 'torrent/:fixhash' => 'torrents#show', :requirements => { :fixhash => /\w{40}/ }
    match 'download/:fixhash' => 'torrents#download', :requirements => { :fixhash => /\w{40}/ }

    match ':banda' => "bandas#show"
    match ':banda/novo_album' => "albuns#new"
    match ':banda/:album' => "albuns#show"
    match ':banda/:album/novo_link' => "links#new"

    match 'album/editar/:id' => "albuns#edit"
    match 'album/excluir/:id' => "albuns#excluir"
    match 'album/destroy/:id' => "albuns#destroy"    

end

app/views/layouts/_container.html.haml
%br/
%br/
#menu{:style => "float:left; width:280px; padding: 15px; border-right: 1px dashed black; margin-right: 30px;"}
  = link_to(image_tag("baixosom.jpg", :border=>0), "/")
  %p
    O BaixoSom é uma inspirada embarcação de referência aos diversos coletivos
    que organizam e distribuem conteúdo pela Internet -
    especialmente às comunidades de Discografias censuradas.
    %br/
    Uma idéia não morre. Viva o P2P!
  = render :partial => "layouts/links"
#meiuca
  = yield

app/views/layouts/_googleanalytics.html.haml
%meta{:content => "_FJXdH6RvWXD7OkAUL2OMu_YIQbWMFHkTCALH2GPqWk", :name => "google-site-verification"}/
:javascript
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
:javascript
  try {
    var pageTracker = _gat._getTracker("UA-3761913-8");
    pageTracker._trackPageview();
  } catch(err) {}

app/views/layouts/_links.html.haml
= link_to 'Som Barato', 'http://sombarato.org/sobre', {:target=>"new"}
%br/
%br/
= link_to 'Partido Pirata do Brasil', "http://partidopirata.org/", {:target=>"new"}
%br/
%br/
%br/
= link_to image_tag('orkut_32.png'), "http://mostre.me/orkut-baixo-gavea", |
  {:target=>"new", :title=>"Comunidade no Orkut"}                          |
-#
= link_to image_tag('twitter_32.png'), "http://twitter.com/baixo_gavea", |
  {:target=>"new", :title=>"Twitter @baixo_gavea"}                       |
%br/
%br/

app/views/layouts/_rodape.html.haml
%table.rodape
  %tr
    %td{:height => "10px", :width => "280px"}
      #stats{:style => "font-size:13px"}
        = "#{@users_count} pessoas > #{@bandas_count} bandas > #{@albuns_count} álbuns"
    %td{:align => "center", :style => "font-size:13px"}
      Copyleft BaixoSom v0.6
    %td{:width => "280px"}
      \&nbsp;

app/views/layouts/_topo.html.haml
#topo
  %table{:align => "center", :style => "margin:0px; padding:0px", :width => "100%"}
    %tr
      %td{:style => "color: white"}
        #login{:style => "width:280px; float:left; text-align:center; vertical-align:middle"}
          - if session[:user]
            - user = User.find(session[:user])
            %b
              Membro #{link_to user.username, user_path(user)}
            | #{link_to "sair", "/logout"}
          - else
            = link_to "Login", "/login"
        - if flash[:notice]
          #status
            = flash[:notice]
          #indice
            - %w{A B C D E F G H I J K L M N O P Q R S T U V W X Y Z #}.each() do |letra|
              = href_menu letra
          :javascript
            $('#indice').hide();
            $('#status').hide();
            $("#status").fadeIn();
            setTimeout(function() {$("#status").fadeOut()}, 4000);
            setTimeout(function() {$("#indice").fadeIn()}, 5500);
                    - flash[:notice] = nil
        - else
          #indice
            - %w{A B C D E F G H I J K L M N O P Q R S T U V W X Y Z #}.each() do |letra|
              = href_menu letra
      = form_for :pesquisar, :url => { :controller=>"pesquisa", :action => "pesquisa" } do |f|
        %td{:align => "right", :style => "color: white", :width => "250px"}
          Pesquise&nbsp;&nbsp;
          %div{:style => "float:right"}= f.text_field 'txt', :size=>20, :class=>"pesquisa"
        %td{:align => "center", :width => "40px"}= image_submit_tag 'find.png', {:style=>"margin-top:5px"}

app/views/layouts/_votos.html.haml
%div{:style => "border: 1px solid gray; padding:5px; background-color:#DAAF85"}
  %p{:style => "padding-left:6px"}
    = image_tag "user_msg.png", {:style=>"float:left; padding-right:8px"}
    %font{:style => "font-size:15px; font-weight:bold"} Comentários
  %table{:cellpadding => "2", :cellspacing => "2px", :width => "100%"}
    - @votos.each do |v|
      %tr{:bgcolor => "#FFEAB7"}
        %td{:align => "left", :colspan => "2", :style => "vertical-align:middle"}
          %div{:style => "float:left; padding-top:3px;"}
            = image_tag "user_16.png", :style=>"float:left; padding: 2px 8px 2px 8px;"
            = link_user_path(v.user)
          %p.menor{:style => "float:right; padding-right:5px"}
            = time_ago v.created_at
            atrás
      %tr{:bgcolor => "white"}
        %td{:valign => "middle"}
          %p
            = image_tag "message.png", :style=>"float:left; padding: 0px 10px 0px 5px;"
            = h v.comentario
        %td{:align => "center", :width => "25px"}= image_voto(v.ponto)
  %hr/
  #comentar{:style => "display:none"}
    - form_for(@voto) do |f|
      - id = @link ? @link.id : @torrent.link.id
      = hidden_field_tag("voto[link_id]", id)
      = hidden_field_tag("voto[user_id]", session[:user])
      %table{:align => "center", :cellspacing => "5"}
        %tr
          %td{:align => "left"} Comentário
          %td{:align => "center"}= image_tag("bom.png")
          %td{:align => "center"}= image_tag("ruim.png")
        %tr{:align => "center"}
          %td{:valign => "top"}= f.text_field(:comentario, {:size=>50, :maxlength=>100})
          %td= f.radio_button(:ponto, "1")
          %td= f.radio_button(:ponto, "-1")
        %tr
          %td{:align => "right"}= f.submit("Enviar")
  %p{:align => "right"}
    %a#butao_comentar.butao{:href => "javascript:void($('butao_comentar').hide()); void($('#comentar').fadeIn());"} Comentar

app/views/layouts/geral.html.haml
%html{:lang => "pt-br", "xml:lang" => "pt-br", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title
      BaixoSom | #{@page_title || "Navegue por Baixo"}
    %link{:href => "/assets/favicon.png", :rel => "shortcut icon"}/
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %meta{:content => "Sistema Colaborativo de Discografias", :name => "description"}/
    = stylesheet_link_tag 'estilo'
    = render :partial => "layouts/googleanalytics" if Rails.env.production?
    = javascript_include_tag "jquery171"
  %body
    = render :partial => "layouts/topo"
    = render :partial => "layouts/container"
    = render :partial => "layouts/rodape"